server:
  extraScrapeConfigs: |
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]  # the module defined in Blackbox Exporter
      static_configs:
        - targets:
          - http://localhost:3000   # your Grafana endpoint
          - https://prometheus.io    # example endpoint
          - http://muiruri.cv/
          - http://muiruri.cv/api/
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
      headers:
        Authorization: "Bearer <YOUR_API_TOKEN>"