apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: muiruri1/cv-backend:v12
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: cv_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_PORT
          value: "5432"
