apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox
  namespace: monitoring
  labels:
    release: prometheus   
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: http
    interval: 30s
    path: /probe
    params:
      module: [http_2xx]